# docker build -t docker.lib.umd.edu/dsteelma/nginx-searchumd:1.0.0 -f Dockerfile-nginx .

# Base image:
FROM nginx

# Install dependencies
RUN apt-get update -qq && apt-get -y install apache2-utils
 
# Set our working directory inside the image
WORKDIR /home/app/webapp
 
# Copy SSL certs
RUN mkdir ssl
 
# Copy Nginx config template
COPY nginx.devel.conf /tmp/docker_example.nginx

EXPOSE 80
 
# Use envsubst to replace templated values in nginx configuration with 
# environment variables.
CMD envsubst '$$SERVER_NAME $$SSL_CERT_PEM_CONTAINER_FULL_PATH $$SSL_CERT_PRIVATE_KEY_CONTAINER_FULL_PATH' < /tmp/docker_example.nginx > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
