# Dockerfile for the generating Varnish Docker image
#
# To build:
#
# docker build -t docker.lib.umd.edu/searchumd-varnish:<VERSION> -f Dockerfile-varnish .
#
# where <VERSION> is the Docker image version to create.

FROM centos:7.6.1810

# Install apt based dependencies required to run Rails as
# well as RubyGems. As the Ruby image itself is based on a
# Debian image, we use apt-get to install those.
RUN yum -y update && \
    yum -y install curl && \
    yum -y install epel-release && \
    curl -s https://packagecloud.io/install/repositories/varnishcache/varnish60lts/script.rpm.sh | bash && \
    yum -y install varnish && \
    yum clean all

COPY docker_config/varnish/ /etc/varnish/

EXPOSE 80

CMD ["varnishd", "-F", "-f", "/etc/varnish/default.vcl", "-a", ":80", "-s", "default,256m", "-p", "feature=+esi_disable_xml_check", "-p", "feature=+esi_ignore_https", "-p", "feature=+esi_remove_bom"]
