# Configuration
#
# Replace the following placeholders with the correct values for
# your installation.
#
# <YOUR_WSKEY>: The "wskey" provided by OCLC
# <YOUR_SECRET>: The "secret" provided by OCLC
# <AUTHENTICATING_INSTITUTION_ID>: The "authenticating institution id" provided
#                                 by OCLC
# <CONTEXT_INSTITUTION_ID>: The "context institution id" provided
#                           by OCLC (typically the same as the institution id)
# <LOADED_LINK>: The base URL to send the query to
# <URL_LINK>: The base URL for result links
# <NO_RESULTS_LINK>: The URL to use when no results are found

defaults: &defaults
  # The following propreties are common to both searchers. If the
  # ebsco_discovery_service_api searcher is not being used, copy these
  # properties into the ebsco_discovery_service_api_article_config.yml file
  username: <%= ENV['EBSCO_DISCOVERY_SERVICE_API_USERNAME'] %>
  password: <%= ENV['EBSCO_DISCOVERY_SERVICE_API_PASSWORD'] %>

  # ebsco_discovery_service_api-specific properties
  loaded_link: 'https://proxy-um.researchport.umd.edu/login?url=https://search.ebscohost.com/login.aspx?direct=true&site=eds-live&bquery='
  url_link: 'https://proxy-um.researchport.umd.edu/login?url=https://search.ebscohost.com/login.aspx?direct=true&site=eds-live'
  no_results_link: 'https://proxy-um.researchport.umd.edu/login?url=https://search.ebscohost.com/login.aspx?direct=true&site=eds-live'

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
